import { router, useLocalSearchParams } from 'expo-router';
import {
  Linking,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from 'react-native';

import { WEB_URL } from '../src/config';
import { colors as C } from '../src/theme';

/**
 * Privacy Policy and Terms of Service, reachable from inside the app.
 *
 * Both stores require a reachable privacy policy given that Howl sends push
 * notifications and hosts user-generated content, and GAPS #35 flagged that the
 * web client had `LegalPage.jsx` while mobile linked to nothing at all.
 *
 * Why this is a summary plus an outbound link rather than the full text:
 * duplicating the web page's prose into a second file guarantees the two drift,
 * and legal text that disagrees with itself is worse than a summary. The web
 * page would be the single source of truth — except it is not addressable by
 * URL yet, because the web client uses a `view` state string instead of routes
 * (GAPS #33). Once that lands, `WEB_URL`/privacy and /terms become real deep
 * links and the "Read the full policy" button can point straight at them.
 *
 * What is below is therefore deliberately the substantive disclosure — what is
 * collected, who processes it, and how to get it deleted — not a paraphrase of
 * the styling.
 */

interface Section {
  heading: string;
  body: string[];
}

const PRIVACY: Section[] = [
  {
    heading: 'What we collect',
    body: [
      'Account: your email address and a hashed password. We never store your password itself.',
      'Profile: your name, age, gender, who you are looking for, location and bio.',
      'Spirit animal profile: the animal, personality traits, avatar description and portrait that Howl generates from your bio.',
      'Activity: your swipes, matches, messages, blocks and reports.',
    ],
  },
  {
    heading: 'AI processing by third parties',
    body: [
      'Your bio is sent to Anthropic (Claude) to choose your spirit animal and write your personality traits and image prompt.',
      'That generated prompt is sent to OpenAI (DALL-E 3) to render your portrait. Your bio is not sent to OpenAI directly.',
      'If you have bot conversations enabled, message text in those conversations is sent to Anthropic to generate replies.',
    ],
  },
  {
    heading: 'Your rights',
    body: [
      'Deletion (GDPR Art. 17 / CCPA): delete your account from the Profile tab. Your account, profile, swipes, matches and messages are removed. Abuse reports filed about you are anonymised rather than deleted, so moderation history survives.',
      'Access and correction: you can view and edit your profile in the app at any time.',
      'We do not sell your personal information.',
    ],
  },
  {
    heading: 'Push notifications',
    body: [
      'If you allow notifications, we store a device push token so we can tell you about new matches and messages. Revoking the permission stops delivery, and signing out removes the token.',
    ],
  },
  {
    heading: 'Age requirement',
    body: ['Howl is for people 18 and over. Accounts found to belong to minors are removed.'],
  },
  {
    heading: 'Contact',
    body: ['Questions or requests: privacy@howl.app'],
  },
];

const TERMS: Section[] = [
  {
    heading: 'Eligibility',
    body: ['You must be 18 or older to use Howl.'],
  },
  {
    heading: 'Acceptable use',
    body: [
      'No harassment, hate speech, sexual content involving minors, impersonation, spam or scams.',
      'Do not scrape the service or attempt to access other people’s accounts or data.',
      'Report anything that breaks these rules using the report button on a profile or message.',
    ],
  },
  {
    heading: 'AI-generated content',
    body: [
      'Your spirit animal, traits and portrait are generated by AI and are not statements of fact about you.',
      'Generation can fail or produce something you dislike. Free accounts can regenerate a portrait once every 30 days.',
    ],
  },
  {
    heading: 'Your content',
    body: [
      'You keep ownership of what you write. You grant Howl the licence it needs to display it in the app and to generate your spirit animal profile from it.',
    ],
  },
  {
    heading: 'Bots and demo accounts',
    body: [
      'Howl seeds demo accounts whose replies are AI-generated. They exist to make the app usable before it has a real user base.',
    ],
  },
  {
    heading: 'No guarantee',
    body: [
      'We do not guarantee matches, message replies, or uninterrupted availability. The service is provided as is.',
    ],
  },
];

export default function LegalScreen() {
  const params = useLocalSearchParams<{ doc?: string }>();
  const isPrivacy = params.doc !== 'terms';

  const title = isPrivacy ? 'Privacy Policy' : 'Terms of Service';
  const sections = isPrivacy ? PRIVACY : TERMS;
  const fullUrl = `${WEB_URL}`;

  return (
    <View style={styles.shell}>
      <ScrollView contentContainerStyle={styles.scroll}>
        <Pressable
          style={styles.back}
          onPress={() => router.back()}
          accessibilityRole="button"
          accessibilityLabel="Go back"
        >
          <Text style={styles.backText}>‹ Back</Text>
        </Pressable>

        <Text style={styles.title} accessibilityRole="header">{title}</Text>
        <Text style={styles.updated}>Summary — last updated August 2026</Text>

        {sections.map(section => (
          <View key={section.heading} style={styles.section}>
            <Text style={styles.heading} accessibilityRole="header">{section.heading}</Text>
            {section.body.map((line, i) => (
              <Text key={i} style={styles.body}>{line}</Text>
            ))}
          </View>
        ))}

        <Pressable
          style={({ pressed }) => [styles.linkButton, pressed && styles.linkButtonPressed]}
          onPress={() => { void Linking.openURL(fullUrl); }}
          accessibilityRole="link"
          accessibilityLabel={`Read the full ${title} on the web`}
          accessibilityHint="Opens your browser"
        >
          <Text style={styles.linkButtonText}>Read the full policy on the web</Text>
        </Pressable>

        <Pressable
          style={styles.switchDoc}
          onPress={() =>
            router.replace({ pathname: '/legal', params: { doc: isPrivacy ? 'terms' : 'privacy' } })
          }
          accessibilityRole="link"
          accessibilityLabel={isPrivacy ? 'Read the Terms of Service' : 'Read the Privacy Policy'}
        >
          <Text style={styles.switchDocText}>
            {isPrivacy ? 'Terms of Service' : 'Privacy Policy'}
          </Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  shell:  { flex: 1, backgroundColor: C.bg },
  scroll: { padding: 20, paddingBottom: 48, maxWidth: 720, width: '100%', alignSelf: 'center' },

  back:     { paddingVertical: 12, alignSelf: 'flex-start', minHeight: 44, justifyContent: 'center' },
  backText: { color: C.textSec, fontSize: 15 },

  title:   { fontSize: 26, fontWeight: '700', color: C.text, marginTop: 4, marginBottom: 4 },
  updated: { fontSize: 13, color: C.textSec, marginBottom: 28 },

  section: { marginBottom: 28 },
  heading: { fontSize: 17, fontWeight: '700', color: C.accentHover, marginBottom: 10 },
  body:    { fontSize: 15, lineHeight: 23, color: C.textSec, marginBottom: 10 },

  linkButton: {
    backgroundColor: C.accent,
    borderRadius: 10,
    paddingVertical: 15,
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  linkButtonPressed: { backgroundColor: C.accentHover },
  linkButtonText:    { color: C.text, fontSize: 16, fontWeight: '600' },

  switchDoc:     { alignItems: 'center', paddingVertical: 16, minHeight: 48, justifyContent: 'center' },
  switchDocText: { color: C.textSec, fontSize: 14, textDecorationLine: 'underline' },
});
