import React from 'react';

export default function LegalPage({ view, setView }) {
  const isPrivacy = view === 'privacy';

  const h = { fontSize: '17px', fontWeight: '700', color: '#553c9a', margin: '0 0 10px' };
  const p = { color: '#4a5568', fontSize: '15px', lineHeight: '1.7', margin: '0 0 10px' };
  const ul = { color: '#4a5568', fontSize: '15px', lineHeight: '1.7', paddingLeft: '22px', margin: '0 0 10px' };
  const section = { marginBottom: '32px' };

  return (
    <div style={{ minHeight: '100vh', background: '#f7fafc' }}>

      {/* Header */}
      <div style={{ background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', padding: '24px 20px 28px' }}>
        <div style={{ maxWidth: '720px', margin: '0 auto' }}>
          <button
            onClick={() => setView('login')}
            style={{ color: 'rgba(255,255,255,0.85)', background: 'none', border: 'none', cursor: 'pointer', fontSize: '14px', marginBottom: '12px', padding: 0 }}
          >
            ← Back to Sign In
          </button>
          <h1 style={{ color: 'white', fontSize: '28px', fontWeight: '800', margin: 0 }}>
            {isPrivacy ? 'Privacy Policy' : 'Terms of Service'}
          </h1>
          <p style={{ color: 'rgba(255,255,255,0.75)', fontSize: '13px', marginTop: '6px', marginBottom: 0 }}>
            Howl · Effective May 4, 2026
          </p>
        </div>
      </div>

      {/* Document body */}
      <div style={{ maxWidth: '720px', margin: '0 auto', padding: '40px 20px 80px' }}>

        {isPrivacy ? (
          <>
            <div style={section}>
              <p style={{ ...p, color: '#718096' }}>
                This Privacy Policy explains what personal information Howl ("we", "us") collects
                when you use our dating app, how we use it, and the rights you have over it.
                By creating an account you agree to this policy.
              </p>
            </div>

            <div style={section}>
              <h2 style={h}>1. Information We Collect</h2>
              <p style={p}>We collect information you provide directly:</p>
              <ul style={ul}>
                <li><strong>Account:</strong> email address and bcrypt-hashed password.</li>
                <li><strong>Profile:</strong> first name, age, location (city/state as a text string), and a personal bio.</li>
                <li><strong>Activity:</strong> swipe decisions (like/pass), matches, and chat messages you send.</li>
              </ul>
              <p style={p}>We generate the following data on your behalf:</p>
              <ul style={ul}>
                <li><strong>Spirit animal profile:</strong> animal type, personality traits, and avatar description produced by Claude AI from your bio.</li>
                <li><strong>Avatar image:</strong> a visual avatar generated by DALL-E 3 from the spirit animal description.</li>
              </ul>
            </div>

            <div style={section}>
              <h2 style={h}>2. How We Use Your Information</h2>
              <ul style={ul}>
                <li>To create and manage your account.</li>
                <li>To show your profile to potential matches and display other users' profiles to you.</li>
                <li>To facilitate messaging between matched users.</li>
                <li>To send password-reset links when you request them.</li>
                <li>To detect and prevent abuse.</li>
              </ul>
              <p style={p}>We do not use your information for advertising, and we do not sell or rent your data to third parties.</p>
            </div>

            <div style={section}>
              <h2 style={h}>3. AI Processing by Third Parties</h2>
              <p style={p}>
                Generating your spirit animal requires sending your bio to <strong>Anthropic</strong> (Claude API)
                and the resulting description to <strong>OpenAI</strong> (DALL-E 3 API). Both providers
                process this data in accordance with their respective privacy policies and API data usage policies.
                Your bio text and avatar prompt are transmitted to these services solely to produce your
                spirit animal profile.
              </p>
              <p style={p}>
                No other personal information (email, name, location, messages) is sent to these providers.
              </p>
            </div>

            <div style={section}>
              <h2 style={h}>4. Information Sharing</h2>
              <p style={p}>Your public profile — name, age, location, spirit animal, personality traits, and avatar — is visible to other Howl users in the Discover and Match views. Your email address and message content are never shared with other users.</p>
              <p style={p}>We do not disclose your information to third parties except: (a) the AI providers described above, (b) infrastructure providers necessary to run the service, and (c) when required by law.</p>
            </div>

            <div style={section}>
              <h2 style={h}>5. Data Retention</h2>
              <p style={p}>
                We retain your data for as long as your account is active. When you delete your account,
                all of your data is permanently removed from our database, including your profile,
                swipes, matches, messages, and password-reset tokens. Avatar image files are also deleted
                from our servers at the time of account deletion.
              </p>
            </div>

            <div style={section}>
              <h2 style={h}>6. Your Rights</h2>
              <p style={p}><strong>Right to deletion (GDPR Art. 17 / CCPA):</strong> You can permanently delete your account and all associated data at any time from your Profile page under Danger Zone. Deletion is immediate and irreversible.</p>
              <p style={p}><strong>Right to access:</strong> You may request a copy of the personal information we hold about you by contacting us at the address below.</p>
              <p style={p}><strong>Right to rectification:</strong> You can update your name, age, location, and bio at any time from your Profile page.</p>
              <p style={p}><strong>California residents (CCPA):</strong> We do not sell personal information. You have the right to know what data we collect and to request deletion, as described above.</p>
            </div>

            <div style={section}>
              <h2 style={h}>7. Security</h2>
              <p style={p}>Passwords are stored as bcrypt hashes and are never stored or logged in plain text. All API communication uses HTTPS. Access tokens are short-lived (30 minutes) and refresh tokens are invalidated on logout and account deletion. We take reasonable technical measures to protect your data, but no system is completely secure.</p>
            </div>

            <div style={section}>
              <h2 style={h}>8. Age Requirement</h2>
              <p style={p}>Howl is intended for users aged 18 and older. We do not knowingly collect information from anyone under 18. If we learn that an account belongs to a minor, we will delete it promptly.</p>
            </div>

            <div style={section}>
              <h2 style={h}>9. Changes to This Policy</h2>
              <p style={p}>We may update this policy from time to time. Material changes will be communicated by updating the effective date at the top of this page. Continued use of Howl after changes constitutes acceptance of the updated policy.</p>
            </div>

            <div style={section}>
              <h2 style={h}>10. Contact</h2>
              <p style={p}>Questions about this policy or requests to exercise your rights: <strong>privacy@howl.app</strong></p>
            </div>
          </>
        ) : (
          <>
            <div style={section}>
              <p style={{ ...p, color: '#718096' }}>
                These Terms of Service govern your use of the Howl dating app. By creating an account
                you agree to be bound by these terms. Please read them carefully.
              </p>
            </div>

            <div style={section}>
              <h2 style={h}>1. Eligibility</h2>
              <p style={p}>You must be at least 18 years old to use Howl. By registering, you confirm that you meet this requirement. We reserve the right to terminate accounts belonging to users who are found to be under 18.</p>
            </div>

            <div style={section}>
              <h2 style={h}>2. Account Registration</h2>
              <p style={p}>You are responsible for maintaining the confidentiality of your account credentials. You must provide accurate information when registering and keep your profile information truthful. You may not create more than one account or create an account on behalf of another person.</p>
            </div>

            <div style={section}>
              <h2 style={h}>3. Acceptable Use</h2>
              <p style={p}>You agree not to:</p>
              <ul style={ul}>
                <li>Harass, threaten, or intimidate other users.</li>
                <li>Send unsolicited commercial messages or spam.</li>
                <li>Post false, misleading, or impersonating content.</li>
                <li>Upload or transmit sexually explicit, violent, or otherwise harmful content.</li>
                <li>Attempt to access another user's account or circumvent any security measure.</li>
                <li>Use the service in any way that violates applicable law.</li>
              </ul>
              <p style={p}>Violations may result in immediate account termination without notice.</p>
            </div>

            <div style={section}>
              <h2 style={h}>4. AI-Generated Content</h2>
              <p style={p}>Your spirit animal, personality traits, avatar description, and avatar image are generated by third-party AI services (Anthropic Claude and OpenAI DALL-E) based on the bio you provide. This content is generated automatically and is for entertainment and social purposes only. It does not constitute psychological analysis, professional advice, or a clinical assessment of your personality.</p>
              <p style={p}>AI-generated content may occasionally be inaccurate or unexpected. You may regenerate your spirit animal at any time by updating your bio.</p>
            </div>

            <div style={section}>
              <h2 style={h}>5. User Content</h2>
              <p style={p}>You retain ownership of any content you submit (bio text, messages). By submitting content you grant Howl a limited license to store and display it as necessary to operate the service. You are solely responsible for the content you post. We reserve the right to remove content that violates these Terms.</p>
            </div>

            <div style={section}>
              <h2 style={h}>6. Privacy</h2>
              <p style={p}>Your use of Howl is also governed by our <button onClick={() => setView('privacy')} style={{ color: '#667eea', background: 'none', border: 'none', cursor: 'pointer', textDecoration: 'underline', fontSize: '15px', padding: 0 }}>Privacy Policy</button>, which is incorporated into these Terms by reference.</p>
            </div>

            <div style={section}>
              <h2 style={h}>7. No Guarantee of Matches</h2>
              <p style={p}>Howl does not guarantee that you will match with any particular person or find a romantic partner through the service. The discover queue and matching system are provided on an "as available" basis. We do not verify the identity or intent of other users.</p>
            </div>

            <div style={section}>
              <h2 style={h}>8. Disclaimers</h2>
              <p style={p}>Howl is provided "as is" and "as available" without warranties of any kind, either express or implied. We do not warrant that the service will be uninterrupted, error-free, or free of harmful components. Avatar images and spirit animal profiles are AI-generated for entertainment purposes and carry no professional or clinical meaning.</p>
            </div>

            <div style={section}>
              <h2 style={h}>9. Limitation of Liability</h2>
              <p style={p}>To the fullest extent permitted by law, Howl and its operators shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the service, including damages from reliance on AI-generated content, interactions with other users, or service interruptions.</p>
            </div>

            <div style={section}>
              <h2 style={h}>10. Account Termination</h2>
              <p style={p}>You may delete your account at any time from the Profile page. We may suspend or terminate accounts that violate these Terms, at our sole discretion, without prior notice. Upon termination, your right to use the service ceases immediately.</p>
            </div>

            <div style={section}>
              <h2 style={h}>11. Changes to These Terms</h2>
              <p style={p}>We may revise these Terms at any time. Material changes will be reflected by an updated effective date. Continued use of Howl after changes take effect constitutes acceptance of the revised Terms.</p>
            </div>

            <div style={section}>
              <h2 style={h}>12. Contact</h2>
              <p style={p}>Questions about these Terms: <strong>legal@howl.app</strong></p>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
